name: 'Run workflow'

# We love stack overflow

on:
  push:
    branches:
      - main    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    name: 'Run workflow'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Run workflow
      env:
        CI_TOKEN: ${{ secrets.FNLOOKUP_ADMIN }}
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" -d "{\"ref\":\"main\"}" "https://api.github.com/repos/FNLookup/encore/actions/workflows/104457934/dispatches"